services:
  database:
    image: 'postgres:16.1'
    container_name: word-trainer-postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=word-trainer'
      - 'POSTGRES_DB=word-trainer'
      - 'POSTGRES_PASSWORD=word-trainer'
volumes:
  postgres_data:
