CREATE TABLE card_contents
(
    card_content_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content         VARCHAR(255),
    language        VARCHAR(255),
    priority        INT,
    card_id         BIGINT,
    CONSTRAINT pk_card_contents PRIMARY KEY (card_content_id)
);

ALTER TABLE card_contents
    ADD CONSTRAINT fk_card_contents_on_card FOREIGN KEY (card_id) REFERENCES cards (card_id);

ALTER TABLE card_contents
    ADD CONSTRAINT unq_card_content UNIQUE (card_id, language, priority);

INSERT INTO card_contents (content, card_id)
SELECT text_side_b, card_id
FROM cards
WHERE text_side_b IS NOT NULL;

UPDATE card_contents
SET language = 'en'
WHERE language IS NULL;

UPDATE card_contents
SET priority = 1
WHERE priority IS NULL;

INSERT INTO card_contents (content, card_id)
SELECT text_side_a, card_id
FROM cards
WHERE text_side_a IS NOT NULL;

UPDATE card_contents
SET language = 'de'
WHERE language IS NULL;

UPDATE card_contents
SET priority = 1
WHERE priority IS NULL;

INSERT INTO card_contents (content, card_id)
SELECT text_side_ua, card_id
FROM cards
WHERE text_side_ua IS NOT NULL;

UPDATE card_contents
SET language = 'ua'
WHERE language IS NULL;

UPDATE card_contents
SET priority = 1
WHERE priority IS NULL;

ALTER TABLE cards
    DROP COLUMN text_side_a;

ALTER TABLE cards
    DROP COLUMN text_side_b;

ALTER TABLE cards
    DROP COLUMN text_side_ua;

UPDATE card_contents
SET content = REPLACE(content, '''', '’')
WHERE content LIKE '%''%';

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('child (sg)', 'en', 2,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'child (sg), children (pl)'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('child', 'en', 3,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'child (sg), children (pl)'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('to write', 'en', 2,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'to write, wrote, written'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('to do', 'en', 2,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'to do, did, done'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('to take', 'en', 2,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'to take, took, taken'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('a hundred and one', 'en', 2,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'a/one hundred and one'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('one hundred and one', 'en', 3,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'a/one hundred and one'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('a hundred and two', 'en', 2,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'a/one hundred and two'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('one hundred and two', 'en', 3,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'a/one hundred and two'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('a hundred and ten', 'en', 2,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'a/one hundred and ten'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('one hundred and ten', 'en', 3,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'a/one hundred and ten'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('a thousand', 'en', 2,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'a/one thousand'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('one thousand', 'en', 3,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'a/one thousand'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('Hi.', 'en', 2,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'Hi., Hello.'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('Hello.', 'en', 3,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'Hi., Hello.'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('I’m', 'en', 2,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'I’m (= I am)'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('I am', 'en', 3,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'I’m (= I am)'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('he’s', 'en', 2,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'he’s (= he is)'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('he is', 'en', 3,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'he’s (= he is)'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('she’s', 'en', 2,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'she’s (= she is)'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('she is', 'en', 3,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'she’s (= she is)'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('they’re', 'en', 2,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'they’re (= they are)'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('they are', 'en', 3,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'they’re (= they are)'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('we’re', 'en', 2,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'we’re (= we are)'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('we are', 'en', 3,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'we’re (= we are)'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('I’d like (to) ...', 'en', 2,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'I’d like (to) ... (= I would like (to)'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('I would like (to)', 'en', 3,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'I’d like (to) ... (= I would like (to)'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('let’s', 'en', 2,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'let’s (= let us)'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('let us', 'en', 3,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'let’s (= let us)'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('Thank you.', 'en', 2,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'Thank you., Thanks.'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('Thanks.', 'en', 3,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'Thank you., Thanks.'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('Goodbye.', 'en', 2,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'Goodbye., Bye.'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('Bye.', 'en', 3,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'Goodbye., Bye.'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('OK', 'en', 2,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'OK (okay)'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('okay', 'en', 3,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'OK (okay)'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('have got', 'en', 2,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'have/has got'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('has got', 'en', 3,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'have/has got'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('mouse (sg)', 'en', 2,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'mouse (sg) , mice (pl)'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('mouse', 'en', 3,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'mouse (sg) , mice (pl)'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('fish (sg)', 'en', 2,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'fish (sg) , fish (pl)'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('fish', 'en', 3,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'fish (sg) , fish (pl)'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('shelf (sg)', 'en', 2,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'shelf (sg) , shelves (pl)'));

INSERT INTO card_contents(content, language, priority, card_id)
VALUES ('shelf', 'en', 3,
        (SELECT c.card_id
        FROM cards c,
             card_contents cc
        WHERE c.card_id = cc.card_id
          AND cc.content = 'shelf (sg) , shelves (pl)'));