name: Github CI/CD

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
#      - name: Run Coverage
#        run: |
#          chmod +x gradlew
#          ./gradlew testCoverage
      - name: Build with Maven and run tests
        run: mvn --batch-mode --update-snapshots verify
      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
#          paths: ${{ github.workspace }}/build/reports/jacoco/testCoverage/testCoverage.xml
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 13
          min-coverage-changed-files: 30
          title: Code Coverage
          update-comment: true